### ISSUE TITLE
p(property)とリストタグの使い方について質問です

### ISSUE THREAD

**Issue by tmmsato** [integrated-design/2015-db2-web#7]
48番佐藤です。
初めて質問させていただきます。
よろしくお願いします。

今回質問したいことは、『p(property)とリストタグ』についてです。
リストタグを使っている場所にpaddingで空白を指定したいため、
「head」に
.padding{

「body」に
p class="padding"
ul
li文字/li
/ul
/p
とコードを書いたのですが、うまくいきませんでした。
（pタグのスタイルと他のタグは併用できないのは分かりました）

ので、検索して「list-style」というタグを発見したのですが、
これはスタイルに
.list-style{
}
と書いて使うものだと思うのですが、<body>にはどのように記述すれば良いでしょうか？
p class="◯◯"
リスト
にしたい
文章
/p
だとなにか足りない気がしましたし、うまくいきませんでした。
長いので、質問を要約すると
・そもそも「list-style」で合っているか
・「list-style」（で合っていたとして）を使う際にどう書けばいいか
です。

うまく説明できない文章、長々と失礼いたしました。
ご回答の方していただけると幸いです。
よろしくお願いします。

佐藤

**Comment by hgw** [comment]
@tmmsato 
初 Issue ありがとう！やりたいこととしては、

> リストタグを使っている場所にpaddingで空白を指定したい

ってことかな？

---

## 箇条書きリストに css で余白をつける方法

 **箇条書きのリスト** を作りたいときは `<p></p>` タグは使わなくてよいです。`<ul><li></li></ul>` だけを使いましょう。

### html

``` html

<!-- 
ここでは仮に padding-list というクラス名にします。なんでもいいけど。 
-->
<ul class="padding-list">
  <li>リスト</li>
  <li>にしたい</li>
  <li>文章</li>
</ul>
```

それから  css で余白(`padding`)を追加します。

### css

``` css

/* 
  padding-list というクラス名は html にあわせて適当に変えてもらっても大丈夫です。 
*/
.padding-list{
  padding-top: 50px;
  padding-left: 50px;
  padding-bottom: 50px;
  padding-right: 50px;
}
```

と、これだけで、 OK だとおもいますー！

---

## list-style の使い方

> 検索して「list-style」というタグを発見したのですが、
> これはスタイルに
> .list-style{
> }
> と書いて使うものだと思うのですが、にはどのように記述すれば良いでしょうか？

`list-style` っていうのは箇条書きに使う **記号の種類を変える** ために使います。

普通、`<ul><li></li></ul>` タグをつかうと、「黒丸」が自動的につくんだけど、

![image](https://cloud.githubusercontent.com/assets/333662/10236476/ea17ee2a-68e0-11e5-9180-3b6cc0d09742.png)

この形を `list-style` でいろいろと変えることができます。詳しくは [HTML クイックリファレンス](http://www.htmq.com/style/list-style-type.shtml) にあります。使うときは、普通に CSS から指定すればいいので、以下のような感じになります。

``` html
<ul class="padding-list">
  <li>リスト</li>
  <li>にしたい</li>
  <li>文章</li>
</ul>
```

``` css
.padding-list{
  padding-top: 50px;
  padding-left: 50px;
  padding-bottom: 50px;
  padding-right: 50px;

  /* 黒丸じゃなくて、白丸にする */
  list-style-type: circle; 
}
```
