### ISSUE TITLE
paddingの使い方がよくわかりません

### ISSUE THREAD

**Issue by hgw** [integrated-design/2015-db2-web#8]
> paddingの使い方がよくわかりません。
> 画像の下にスペースを空けたい場合はstyleの中はどのようにかいたらいいですか。
> 
> あと、背景の色指定が1つのページだけでなくぜんぶのページに反映されてしまいます。

**Comment by hgw** [comment]
以下のように書くと `class="with-space"` とクラスのついた要素にスペースをつけることができます。

``` css
/* 
  .with-space というのは任意の名前を適当に付けてもらって OK です
 ドット 「.」 をお忘れなく！
*/
.with-space{
  padding-bottom: 50px;
}
```

``` html
<img src="画像へのパス" alt="" class="with-space">

<!-- img 以外にも p とか div にももちろん使えます。-->

<p class="with-space">下に 50px の padding が付きます</p>

<div class="with-space">下に 50px の padding が付きます</div>
```

**Comment by hgw** [comment]
> あと、背景の色指定が1つのページだけでなくぜんぶのページに反映されてしまいます。

CSS は基本的に上書きされていきます。つまり後ろに書いた指定が優先的に反映されます。

``` css
/* 
  例えばこう書くと…
*/ 
body {
  background-color:white;
}

/* 
  こちらの指定が優先されます
  背景色は赤になります
 */ 
body {
  background-color:red;
}
```

なので、それぞれのページで別の指定をしたい時は上書きされないように、別のクラスをあてるといいと思います。

## ページごとに背景色を変える

#### css

``` css
body.white-page {
  background-color:white;
}

/* 
  こちらの指定が優先されます
  背景色は赤になります
 */ 
body.red-page {
  background-color:red;
}
```

#### 白い背景にしたいページ

``` html
<html>
<head>
  <link rel="stylesheet" href="style.css">
</head>
<body class="white-page">
白い背景にしたいページ
</body>
</html>
```

#### 赤い背景にしたいページ

``` html
<html>
<head>
  <link rel="stylesheet" href="style.css">
</head>
<body class="red-page">
赤い背景にしたいページ
</body>
</html>
```
