### ISSUE TITLE
html でライン(横棒) のひきかたがわかりません

### ISSUE THREAD

**Issue by hgw** [integrated-design/2015-db2-web#9]
> html でライン(横棒) のひきかたがわかりません

**Comment by hgw** [comment]
ただの装飾された横棒を引くときは `<hr>` を使うといいと思います。

#### css

``` css

.green-border {
  height: 10px;   /* 棒の太さは 10px */
  border: none;   /* デフォルトでボーダーがついてしまうので、トル */
  background-color: green;
}

.red-border {
  height: 20px;   /* 棒の太さは 20px */
  border: none;   /* デフォルトでボーダーがついてしまうので、トル */
  background-color: red;
}

```

#### html

``` html
<hr class="green-border">
上にみどりの横棒を、下に赤色の横棒をびーーーーーーーーっとひきます。
<hr class="red-border">
```

#### 結果

![image](https://cloud.githubusercontent.com/assets/333662/10308867/d924d682-6c73-11e5-82a2-c8124d9ea5ce.png)

---

もちろん css で `border` を使ってやる方法もあるので、どちらでも :ok_hand: ですー。
